name: hygie
description: hygie app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  cupertino_icons: ^0.1.2
  flutter_signin_button: ^1.0.0
  google_sign_in:
  apple_sign_in: ^0.1.0
  flutter_svg: ^0.17.4
  cloud_firestore: ^0.13.6
  cached_network_image: ^2.2.0+1
  flutter_datetime_picker: ^1.3.8
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/welcome.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/music/meditation.mp3


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400
    - family: Tillana
      fonts:
        - asset: assets/fonts/Tillana-Regular.ttf
        - asset: assets/fonts/Tillana-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tillana-Medium.ttf
          weight: 400


